
ALTER TABLE league_players 
ADD COLUMN IF NOT EXISTS total_break_and_runs INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_rack_and_runs INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_nine_on_snap INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_win_zip INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_early_8 INTEGER DEFAULT 0;
