
ALTER TABLE league_players 
ADD COLUMN IF NOT EXISTS matches_played INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS matches_won INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS matches_lost INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS breakpoint_racks_won INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS breakpoint_racks_lost INTEGER DEFAULT 0;
