-- Add stat columns to games table
ALTER TABLE games 
ADD COLUMN IF NOT EXISTS is_break_and_run BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_rack_and_run BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_early_8 BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_8_wrong_pocket BOOLEAN DEFAULT FALSE;
